- src/NuGetizer.Tasks/NuGetizer.Shared.targets
- src/NuGetizer.Tasks/dotnet-nugetize.targets
This was breaking when using dotnet-nugetize.
> Make sure we never get duplicate NuspecFile items

- src/NuGetizer.Tasks/NuGetizer.Authoring.NoTargets.props
- src/NuGetizer.Tasks/NuGetizer.Authoring.NoTargets.targets
- src/NuGetizer.Tasks/NuGetizer.Authoring.props
- src/NuGetizer.Tests/Builder.NuGetizer.cs
- src/NuGetizer.Tests/given_a_notargets_sdk_project.cs
This allows using that SDK for packaging projects if desired. This change allows referencing such projects from other packaging projects, and also from regular Microsoft.NET.Sdk projects too.
> Add support for Microsoft.Build.NoTargets SDK

- .github/workflows/build.yml
- README.md
- src/NuGetizer.Tasks/NuGetizer.Cleanup.targets
- src/NuGetizer.Tasks/NuGetizer.Shared.targets
- src/NuGetizer.Tasks/NuGetizer.props
When working with packages built locally, it's quite common to dogfood those packages from sample projects locally. This can use a fixed package version for the locally produced packages, or auto-incremented versions. Also, the referencing projects might choose to use wildcards when testing local packages too.
The caching mechanisms built into NuGet make this process a bit more cumbersome than necessary: if you build a fixed version package, you will never get a newly built version restored in a project elsewhere in the machine because NuGet will believe the one in the cache is already the latest. The HTTP-level cache implemented on top of the package cache also works against you in that case even if you clean that folder. And wildcards don't make things much better unless you clean those …
> Add automatic cleanups to improve the inner devloop

- README.md
- src/NuGetizer.Tasks/NuGetizer.Inference.props
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.props
- src/NuGetizer.Tests/Builder.NuGetizer.cs
- src/NuGetizer.Tests/Scenarios/Scenario.props
- src/NuGetizer.Tests/Scenarios/Scenario.targets
- src/NuGetizer.Tests/Scenarios/given_a_library/library.csproj
- src/NuGetizer.Tests/given_a_library.cs
Like the target framework attribute and assembly info.
Additional exclusions should be configurable as needed, so we moved the <PackInference> item to a .props file so the project can update/remove as needed.
This adds another customization point too, allowing to tweak the exclusions for any PackInference (i.e. for Content, EmbeddedResource, None and so on).
> By default, packing Compile should not include generated files

- README.md
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/Scenarios/given_a_library_with_content/library_with_content.csproj
- src/NuGetizer.Tests/given_a_library_with_content.cs
Add doc note on TargetPath and how it's used (also with Link), and make sure we don't overwrite the provided one by the user if it's present.
> If an item provides TargetPath, preserve it as relative to the PackFolder

- src/NuGetizer.Tasks/NuGetizer.Cleanup.targets
When using dotnet build, the ordering is slightly different than msbuild, so adding to PackDependsOn is more reliable.
Fixes #22
> Make sure the output package cleanup happens before Pack

- src/NuGetizer.Tasks/NuGetizer.Shared.targets
- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
Because we were importing the compatibility props only from the non-multitargeting targets, the defaulting of PackOnBuild from GeneratePackageOnBuild was not being applied and that caused usage of that property to fail in multi-targeting projects.
By bringing in the compat props from the shared targets (used in both single and multi targeting scenarios), we can properly default all values in all types of builds.
Fixes #34
> Import compatibility props for multi-targeting too

- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/Scenarios/given_multitargeting_libraries/common.csproj
- src/NuGetizer.Tests/Scenarios/given_multitargeting_libraries/uilibrary.csproj
- src/NuGetizer.Tests/Scenarios/given_multitargeting_libraries/uishared.csproj
- src/NuGetizer.Tests/given_multitargeting_libraries.cs
When MSBuild project references are resolved, in multi-targeting P2P references, the `SetTargetFramework` metadata is populated with the nearest target framework supported by the referenced project (from the referencing project's point of view). For example, if a `netcore3.1` project references a `net5.0;netstandard2.1` one, when resolving the contents for the referenced project, the built-in targets will properly calculate (using the NuGet-provided GetReferenceNearestTargetFrameworkTask task) the target framework compatible with the referencing project.
If we don't set the target framework, we end up inadvertently invoking targets on the project reference using the *calling* project target framework (in this case `netcoreapp3.1`), which is not supported by the referenced project and we …
> When resolving P2P references for packaging, set target framework

- src/NuGetizer.Tasks/NuGetizer.MultiTargeting.targets
- src/NuGetizer.Tests/given_a_multitargeting_library.cs
We already add `GetTargetPathWithTargetPlatformMoniker` for multi-targeting, but `GetTargetPath` is probably more common, so we add it with the same pattern used in the built-in targets.
> Add more common GetTargetPath to multi-targeting

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
This makes it behave just like PackagePath/PackFolder, and avoids having to explicitly add `Pack=true` after you specified `PackageReference`.
For example:
<None Include='lib\netstandard2.0\Newtonsoft.Json.dll' PackageReference='Newtonsoft.Json' />
Will now automatically be packed. The existing inference rules about target path/package path still apply, and in this case it will mean the file is packed to the same relative path as the referenced file in the source package reference.
Fixes #44
> When using PackageReference metadata infer Pack=true

- src/NuGetizer.Tasks/NuGetizer.Compatibility.props
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_packagereferences.cs
From NuGet/Home#6354, the SuppressDependenciesWhenPacking property can turn off package reference and framework reference dependencies inference in SDK pack.
This adds compatibility behavior that turns off packing of PackageReference by default when that flag is true, as well as framework references.
The individual package references can still opt in even when the setting is true.
Fixes #67
> :wastebasket: Add support for compatibility SuppressDependenciesWhenPacking property

- src/NuGetizer.Tasks/NuGetizer.Compatibility.props
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_packagereferences.cs
The new PackDependencies property (defaults to empty, meaning `true`) can be set to `false` which is equivalent to setting `SuppressDependenciesWhenPacking=true`.
This allows quickly and easily opting out of PackageReference (defaults all item's Pack metadata to false) as well as framework references.
Fixes #73.
> Add support for opting out of dependencies packing

- .github/workflows/build.yml
- .netconfig
- src/Directory.Build.props
- src/Directory.Build.targets
- Checkout submodules recursively for dotnet-format step https://github.com/devlooped/oss/commit/4bc9de2
- Only set signing keyfile if it exists at default location https://github.com/devlooped/oss/commit/637662d
- Improve strong-naming properties defaults https://github.com/devlooped/oss/commit/c9924b5
- Allow projects to preserve default EmbeddedResource item behavior https://github.com/devlooped/oss/commit/f19d5dd
- Add a CI constant for use in code to detect CI-built code https://github.com/devlooped/oss/commit/e7de4d0
> Bump files with dotnet-file sync

- src/NuGetizer.Tasks/CreatePackage.cs
- src/NuGetizer.Tasks/NuGetizer.PackageMetadata.targets
The short SHA (9-char version) is sufficiently unique for use to retrieve the upstream commit/tree.
Whenever the short sha is available, we should use that instead. An opt-out property UseShortSourceRevisionId allows turning off this behavior.
Fixes #94
> If short SHA is available, use it for package metadata

- readme.md
- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/given_projectreferences.cs
This is far simpler and more aligned with the way we allow PackFolder on almost any item.
Fixes #124 and improves on #118.
> Allow specifying PackFolder in ProjectReference

- src/NuGetizer.Tasks/EvaluateWildcards.cs
- src/NuGetizer.Tasks/Extensions.cs
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.csproj
- src/NuGetizer.Tests/given_packinference.cs
We were previously assuming Exclude was a valuated while doing the Include for entire item groups, while this is not the case. We need instead to evaluate using the same MSBuild syntax (we use minimatch for this) so we can properly exclude items.
Fixes #128 and #122
> Properly evaluate PackInference.PackExclude

- src/dotnet-nugetize/EmbeddedResource.cs
- src/dotnet-nugetize/Program.cs
- src/dotnet-nugetize/after.sln.targets
- src/dotnet-nugetize/dotnet-nugetize.csproj
Rather than failing ungracefully, just skip those project where we can safely detect nugetizer isn't installed.
Fixes #107
> Skip non-nugetized projects when nugetizer runs for solution

- src/NuGetizer.Tasks/NuGetizer.Cleanup.targets
Hi,
Thank you very much for this fantastic tool, it's so much easier to create complex NuGet packages with this tool.
When I applied it to my projects, I found  a few small issues with incremental build: NuGetizer fails to clean generated NuGet packages in some cases:
- When version components contain more than one digits, like "11.22.33";
- When "PackageOutputPath" has been set to locations outside of intermediate directory.
I also find it's very difficult to change NuGet cache location, which I usually pointed to a non-default one for testing purpose.
I fixed all those issues in this pull request, tested with my projects. Please have a check.
Regards!
Guopeng
> A few fixes for cleanup targets

- src/NuGetizer.Tasks/Extensions.cs
We had code to account for [this scenario](https://github.com/dotnet/sdk/issues/9718#issuecomment-419390506) but it wasn't working properly because we included the backslash (which in non-Windows might not even be there), so we improve the partial path detection and it should now work as expected.
Fixes #143
> Fix contentFiles relative path in manifest

- src/NuGetizer.Tasks/NuGetizer.targets
For cases where you know you'll be authoring a package you want to only target to a specific framework, you are now able to specify so by setting `BuildOutputFrameworkSpecific=true` in the project.
Alternatively, you can also annotate a project reference to the packaging project with the TFM you want it to "pack for" as:
```xml
<ProjectReference Include="Common.msbuildproj" TargetFramework="net6.0"
```
Fixes #155
> Allow specifying that packaging projects are framework specific

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.props
This makes the `PackFolder=buildTransitive` behave as if it were `build`, which makes the most sense.
Partially fixes #139
Fixes #179
> Add support for buildTransitive pack folder kind

- src/NuGetizer.Tasks/NuGetizer.props
- src/NuGetizer.Tasks/NuGetizer.targets
Whenever we had `PrivateAssets=all` on a project reference (whether implicitly or explicitly), we used to unconditionally pass `PackFolder=$(PackFolder)` when resolving referenced content. This is correct whenever the calling project does indeed have a `PackFolder`, but not for packaging projects, since in that case, the packaging project itself doesn't have a value for that property (since it can pack any arbitrary content and has no primary output).
So we switch to the mechanism used already by the .NET SDK (and common targets) of using a metadata item with the full property assignment syntax. This means that if the metadata isn't present (which we now condition to the presence of a value for `PackFolder`), when calling `GetPackageContents` on the project reference, no value will be …
> Be smarter about PackFolder on project references

- src/NuGetizer.Tasks/AssignPackagePath.cs
- src/NuGetizer.Tasks/NuGetizer.Authoring.props
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.props
- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/AssignPackagePathTests.cs
- src/NuGetizer.Tests/Builder.NuGetizer.cs
- src/NuGetizer.Tests/Scenarios/given_a_packaging_project/b/b.csproj
- src/NuGetizer.Tests/given_a_packaging_project.cs
- src/NuGetizer.Tests/given_projectreferences.cs
We refine the support for packaging projects in this commit, by defaulting its PackFolder to Ignore, which becomes somewhat similar to None, but allows for differenciation.
Moreover, we test specific scenarios involving a packaging project becoming framework-specific (which we previously didn't explicitly support) by means of setting `BuildOutputFrameworkSpecific=true` at the project level. This requires re-targeting referenced assets whenever that property is true, in addition to non-packaging projects in that same scenario.
Fixes #182
> Allow packaging projects to be framework-specific

- src/NuGetizer.Tasks/NuGetizer.Authoring.NoTargets.Defaults.targets
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/Builder.NuGetizer.cs
- src/NuGetizer.Tests/given_a_packaging_project.cs
Make it so that the default behavior for None items when the PackFolder for the project is build or buildTransitive the None matches the project. This is unless the item doesn't specify a different FrameworkSpecific or PackFolder metadata.
This fixes the default items that were not being properly populated for packaging projects too, due to the lack of a default file extension (meaning all default items end up being ignored).
Fixes #184.
> Improve default heuristics for build projects

- readme.md
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/NuGetizer.Tests.csproj
- src/NuGetizer.Tests/given_a_packaging_project.cs
A readme.md file at the project level will typically be automatically included as a None item,
which by default won't pack either.
This improves the inference by adding a `PackReadme=true` (by default) which controls whether a readme file (either explicitly specified with `PackageReadmeFile` as per the SDK Pack spec, or implicitly found alongside the project) is automatically packed and set as the Readme package metadata (as long as the project is being packed (IsPackable=true)).
NOTE: this is implemented in the Inference targets, so that when inference is turned off entirely,
this doesn't happen automatically, for consistency with other items inferences.
Fixes #185
> Improve readme content inclusion metadata inference

- src/NuGetizer.Tasks/NuGetizer.Compatibility.props
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_a_tool_project.cs
This brings nugetizer pretty much to parity with SDK Pack for CLI tools too :).
We leverage the SDK tool packing targets to determine the files to pack, but otherwise preserve nugetizer's inference and packing behavior. Best of both worlds!
The new `InferToolContents` target is the one that transforms the `PackTool` target's `TfmSpecificPackageFile` into our own `None` items for packing. It can also be extended to trim the tool's contents via a custom target that removes items, such as::
```xml
<Target Name="TrimRuntimes" AfterTargets="InferToolContents">
<ItemGroup>
<None Remove="@(None)" Condition="$([MSBuild]::ValueOrDefault('%(None.PackagePath)', '').Contains('/runtimes/'))" />
</ItemGroup>
</Target>
```
(this target would remove all runtimes from the tool package, but otherwise …
> Improve compatibility with SDK Pack for tools

- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
- src/NuGetizer.Tests/NuGetizer.Tests.csproj
We were previously not re-targeting dependencies from referenced (non-packing) projects, which would end up as dependencies in the originating project TFM, instead of the packing (TFM-specific) project, causing a runtime failure since the dependency wouldn't be present, even if the referenced assembly would.
This is now supported, including in multi-targeting scenarios for the packing project.
Fixes #199
> Support transitive package dependency from P2P

- src/NuGetizer.Tests/NuGetizer.Tests.csproj
The root cause analysis was performed in https://github.com/dotnet/msbuild/issues/7873.
By upgrading to latest MSBuild 17.3.1, the issue is resolved.
> Latest agents with .net48 fail to run tests due to missing method

- .github/workflows/build.yml
- .github/workflows/publish.yml
- Directory.Build.rsp
Since the test build/run step is run in pwsh, the expression
to set the version isn't working, but we don't need that anyway,
since `pack` will already pass the right version and will end
up causing a new build.
> Generate and upload binlogs, don't version test build/run

- src/NuGetizer.Tasks/CreatePackage.cs
- src/NuGetizer.Tasks/IncludesResolver.cs
- src/NuGetizer.Tests/IncludesResolverTests.cs
This makes it easier to troubleshoot include authoring mistakes.
Fixes #232
> When include in readme fails, log a warning

- src/dotnet-nugetize/Program.cs
For dotnet tool projects, the design-time build we performed failed since the tool attempted to publish its output, which the project references weren't able to supply and the whole thing failed with missing files.
We now pass IsPublishable=false to fake a sort of "DTB" for tools too, so they don't attempt to publish output.
Fixes #247
> Don't fail nugetize for tools

- src/NuGetizer.Tasks/NuGetizer.Compatibility.props
- src/NuGetizer.Tasks/NuGetizer.PackageMetadata.targets
- src/NuGetizer.Tasks/NuGetizer.Shared.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
We should support the OOb SDK Pack property instead. In this case, it's intuitive enough and will likely get completion support eventually, as well as docs.
See https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference
Fixes #253
> Make IsDevelopmentDependency legacy

- readme.md
In the README file's "Dynamically Extending Package Contents" section, wrap the `<PackageFile />` elements in an `ItemGroup`
> Add missing ItemGroup to MSBuild snipped

- src/NuGetizer.Tasks/NuGetizer.Shared.targets
This allows P2P references to inspect this value in a standard way that is consistent with package references.
Resolved assets via NuGet always contain this item metadata, so it makes sense to add it to a referenced project's output for consistency. In the case of analyzers, this could be helpful in filering analyzers by their package id in both cases in a uniform way.
> Add NuGetPackageId metadata to target path item

- src/NuGetizer.Tasks/NuGetizer.Shared.targets
This is used by dotnet-releaser to get package properties, but also may help ensure assembly-level attributes are also properly populated with the right values at AssemblyInfo generation time.
> Ensure package metadata is populated before GetAssemblyVersion

- src/NuGetizer.Tasks/NuGetizer.props
By default, it should not appear, since otherwise it seems like something's broken when it's not. PackageFiles can reference arbitrary things that are not necessarily physical files so they can show up as broken file references.
Should improve the experience for cases like https://github.com/devlooped/nugetizer/issues/263#issuecomment-1418958506
> PackageFile should be hidden from solution explorer

- src/Directory.props
- src/Directory.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.csproj
- src/dotnet-nugetize/dotnet-nugetize.csproj
We don't need ALL of the ThisAssembly generators, just the ones we use
> Reduce dependency surface on ThisAssembly, remove older local stuff

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
- src/NuGetizer.Tests/NuGetizer.Tests.csproj
- src/NuGetizer.Tests/given_a_library_with_private_assets_reference.cs
We were previously using a combination of @(ReferencePath) and @(_ReferenceRelatedPaths) to determine the candidate libs to pack as private, but this was incorrect since we would still sometimes pack ref assemblies.
Turns out that this is an issue that surfaced elsewhere (see https://github.com/NuGet/Home/issues/9310#issuecomment-612307251) which resulted in a new output group being available from the common MSBuild targets (see https://github.com/dotnet/msbuild/issues/3069) that we can use instead to do this properly.
Closes #263
> Pack runtime lib assets when inferring dependencies

- NuGetizer.sln
- src/CodeAnalysis/CodeAnalysis.csproj
- src/CodeAnalysis/SponsorLinker.cs
- src/Directory.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.csproj
See https://github.com/devlooped/SponsorLink and https://www.cazzulino.com/sponsorlink.html.
> Add SponsorLink to ensure ongoing development and maintenance

- readme.md
- src/NuGetizer.Tasks/CreatePackage.cs
- src/NuGetizer.Tasks/MetadataName.cs
- src/NuGetizer.Tests/CreatePackageTests.cs
- src/NuGetizer.Tests/InlineProjectTests.cs
We currently surface the PackageReference's IncludeAssets/ExcludeAssets as the ultimate dependency Include/Exclude metadata attributes. This is not always what you want, though.
For example: if you need the compile dependency for compiling the project, but only want to surface the dependency as a build dependency, you cannot exclude the compile asset because your project depends on the lib to build.
In order to make this more intuitive and aligned with the other attributes, we introduce PackInclude/PackExclude attributes for that purpose, which map exactly to the .nuspec: https://learn.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element.
Note that the existing behavior will be overriden if those attributes are provided, which provides backwards compatibility.
> Support Include/Exclude attributes from Dependency

- src/CodeAnalysis/CodeAnalysis.csproj
When referencing NuGetizer, no SponsorLink APIs should be exposed to consumers
> Only surface build and analyzer from SponsorLink

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.props
- src/NuGetizer.Tests/Scenarios/given_multitargeting_libraries/uilibrary.csproj
- src/NuGetizer.Tests/given_multitargeting_libraries.cs
Turns out that the new-ish platform-suffixed TF names (i.e. net7.0-windows, net7.0-maccatalyst and so on) all end up being the same TFM (.NETCoreApp, Version=7.0), which ends up packing assets to duplicate package paths in pack inference.
It seems like we might need to rethink nugetier reliance on the TFM for most of its multi-targeting and TF-specific packing. We currently use the TFM as the default to determine target package path, unless a TF is specified for an item. This ends up being incorrect if the TF contains a platform suffix, as noted.
For now, provide a specific and localized fix for just primary output assembly, symbols and docs.
We should do an extensive examination of other scenarios for xplat MAUI packages.
> Fix support for platform-suffixed build output

- src/NuGetizer.Tasks/AssignPackagePath.cs
- src/NuGetizer.Tasks/CreatePackage.cs
- src/NuGetizer.Tasks/Extensions.cs
- src/NuGetizer.Tasks/MetadataName.cs
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.MultiTargeting.targets
- src/NuGetizer.Tasks/NuGetizer.props
- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/AssignPackagePathTests.cs
- src/NuGetizer.Tests/CreatePackageTests.cs
- src/NuGetizer.Tests/UtilitiesTests.cs
- src/NuGetizer.Tests/given_multitargeting_libraries.cs
We previously (ab)used the TargetFrameworkMoniker of a project as a default/fallback target framework to use whenever the TargetFramework metadata was not present for a particular PackageFile.
This broke down in .NET5+ when platform-suffixed TFs such as "net7.0-windows" now need the target platform version, in addition to the TF< which, furthermore, can no longer be recreated as a nuget framework from the TFM alone, since it also contains the TargetPlatformIdentifier.
So rather than complicating the previous single metadata value with *three* (TFM, TPM and a boolean on whether the original TF had a platform suffix or not), we instead normalize this up-front in all projects via a new target, and set this as PackTargetFramework. We then proceed to use this in a new more intention-revealing …
> Improve the handling of platform-suffixed target frameworks

- src/Directory.props
- src/dotnet-nugetize/Program.cs
- src/dotnet-nugetize/dotnet-nugetize.csproj
Switch to Spectre.Console and a treeview.
Before:
After:
> Improve package rendering in dotnet-nugetize

- src/dotnet-nugetize/Program.cs
We were showing MSBuild output for any nugetize run that took longer than 10 seconds. Diagnosing slow builds shouldn't be a nugetizer issue, and it makes it confusing to see potentially many warnings and what-not that are irrelevant to packing.
Make it so instead of asking for quiet, you can ask for verbose and get the output.
If there were errors running the tool, we'd still want to see the MSBuild output, though.
> Change nugetize default to non-verbose

- src/Directory.props
- src/Directory.targets
These are always ignored and can therefore be tweaked without fear of inadvertently checking them in.
> Allow extending the build with local-only targets

- src/dotnet-nugetize/Program.cs
This makes it easier to take screenshots without revealing full local paths, while still preserving the click-ability of those file links if the terminal supports it.
> Render nuspec as a relative path to the nugetize output

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
.NET 7.0 SDK changed from:
```xml
<ResolvePackageDependencies
ProjectPath="$(MSBuildProjectFullPath)"
ProjectAssetsFile="$(ProjectAssetsFile)"
ProjectLanguage="$(Language)"
EmitLegacyAssetsFileItems="$(EmitLegacyAssetsFileItems)"
TargetFramework="$(TargetFramework)"
ContinueOnError="ErrorAndContinue">
<Output TaskParameter="PackageDefinitions" ItemName="PackageDefinitions" />
<Output TaskParameter="PackageDependencies" ItemName="PackageDependencies" />
<Output TaskParameter="TargetDefinitions" ItemName="TargetDefinitions" />
<Output TaskParameter="FileDefinitions" ItemName="FileDefinitions" />
<Output TaskParameter="FileDependencies" ItemName="FileDependencies" />
</ResolvePackageDependencies>
```
to:
```xml
<ResolvePackageDependencies
ProjectPath="$(MSBuildProjectFullPath)" …
```
> Ensure transitive dependencies are properly resolved for inference

- readme.md
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_a_tool_project.cs
- src/dotnet-nugetize/Program.cs
We have an SDK-compatible mechanism for packing .NET tools: PackAsTool. This satisfies a very specific scenario for .NET tools, but doesn't work for regular CLI tools that don't need packing as standalone dotnet tools.
For these CLI tools, packing the output of Publish makes much more sense, and results in way fewer customizations in package references.
We introduce a new property, PackAsPublish, which is initialized to `true` whenever the project is publishable and a cross-platform executable (pending widening the definition upon feedback). In this case, we don't infer content from package dependencies and references with copy local and so on, but rather rely exclusively on Publish doing its work. We don't change the PackFolder treatment, so that property is orthogonal to PackAsPublish, …
> Pack console apps using publish output by default

- src/dotnet-nugetize/Program.cs
The rendering will still be the relative path for better privacy in screenshots.
> Fix link for nuspec by using full path in actual link

- src/dotnet-nugetize/Program.cs
This is useful information for package authors, render similar to how we render content extra attributes.
> Render include/exclude attributes in dependencies

- src/dotnet-nugetize/after.sln.targets
Project dependencies is a mechanism to affect the build order in a solution without adding project references. See https://www.cazzulino.com/project-dependencies-as-project-references.html.
In this scenario, MSBuild will emit a .metaproj for the solution and *also* a .metaproj for each project that declares such dependencies, which in turn uses project references for the dependencies *and* the original project. This generated .metaproj, obviously, won't have any of the standard targets, not even GetTargetPath, which means we won't be able to even determine if the project is nugetized or not.
This used to cause the nugetize tool to refuse to process the other projects in a solution.
This change removes such meta projects from the solution so that the other projects can still work. Note …
> Fix nugetize tool for solutions that use project dependencies

- src/dotnet-nugetize/dotnet-nugetize.csproj
We don't need to limit to .net6
> Allow running nugetizer on any major .NET version

- readme.md
- src/NuGetizer.Tasks/NuGetizer.PackageValidation.targets
- src/NuGetizer.Tasks/NuGetizer.Shared.targets
- src/NuGetizer.Tasks/readme.md
- src/NuGetizer.Tests/InlineProjectTests.cs
Package validation is increasingly important for multi-targeting libraries, so NuGetizer must be compatible with this feature which became first available in the .NET6 SDK.
In addition to adding the basic compatibility, we also turn the feature on by default (setting EnablePackageValidation=true) for multi-targeting projects when building in Release mode, to ensure best-practices are applied by default.
Users can opt-out of this by setting it to `false` instead explicitly.
> Add compatibility with SDK package validation

- src/dotnet-nugetize/Program.cs
No point in rendering what's effectively a default value that should never have existed in the first place. NuGetizer flags this as a warning even now.
> For nugetize tool, consider default description as empty

- src/CodeAnalysis/CodeAnalysis.csproj
- src/CodeAnalysis/MetadataAnalyzer.cs
- src/CodeAnalysis/NuGetizer.CodeAnalysis.targets
- src/CodeAnalysis/Resources.resx
- src/NuGetizer.Tasks/NuGetizer.Shared.targets
The SDKs set this default in Microsoft.NET.DefaultAssemblyInfo.targets, but it's not really a very useful default (like the Description one).
So we flag this as a warning now.
We take over NG0102 since that wasn't active in any way (analyzers never get 4k chars of a property anyway).
> Add warning when Authors == AssemblyName

- src/NuGetizer.Tasks/dotnet-nugetize.targets
- src/dotnet-nugetize/Program.cs
- src/dotnet-nugetize/after.sln.targets
This default value, just like the default description, is now a warning and we shouldn't emit it, to keep the actually used metadata more prominent.
> In nugetize tool, skip Authors metadata if it equals AssemblyName

- src/NuGetizer.Tasks/AssignPackagePath.cs
- src/NuGetizer.Tasks/Extensions.cs
- src/NuGetizer.Tasks/NuGetizer.Tasks.csproj
- src/NuGetizer.Tests/InlineProjectTests.cs
Consider the scenario where we include multiple files from a relative path that's outside the project directory:
<PackageFile Include="..\..\docs\**\*.*" PackagePath="docs\" />
In this case, the natural expectation is that starting from the wildcard, the paths are reconstructed under the specified target package path, just as if we had added %(RecursiveDir)%(Filename)%(Extension) at the end of the `docs\` expression.
We don't do that right now, just appending a relative path that is invalid since it goes outside the package root scope (we add the full `..\..\` as part of concatenating the `RelativeDir`, which includes that).
Granted, this can be worked-around by just constructing the right package path via MSBuild or setting a Link property, but it should Just Work OOB.
This commit adds …
> Improve support for recursive dir inclusion

- readme.md
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_packinference.cs
Added a new `PackSatelliteDlls` property that can be set to `false` to avoid packing the satellite resource assemblies when the project is localized. This setting only applies when `PackBuildOutput=true`.
When a `PackageReference` has `PrivateAssets=all`, we assume all assets should be packed alongside the primary output (just as you would see them in the build output). Package references that include satellite resources will show up in the output directory, so it makes sense to also pack them in this case.
> Automatically pack dependencies satellite resources for private packages

- src/CodeAnalysis/CodeAnalysis.csproj
- src/CodeAnalysis/NuGetizer.CodeAnalysis.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
Otherwise, we'd get SL001 for misconfiguration
> Properly pack and import SL targets from NuGetizer

- src/CodeAnalysis/NuGetizer.CodeAnalysis.targets
Since the description can contain newlines that will break the emitted editorconfig file with the values, only include in the specific scenario where we ensure the description isn't equal to the default.
> Don't include Description as compiler metadata unconditionally

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_packinference.cs
When dependency has a wildcard, we can use the exact same approach we use to resolve empty version in centrally managed package versions.
Fixes #64
> Resolve wildcard dependency just like central package versions

- src/NuGetizer.Tasks/InferImplicitPackageReference.cs
- src/NuGetizer.Tests/InferImplicitPackageReferenceTests.cs
We should never traverse and infer implicit transitive dependencies for packages that are already directly referenced by the project.
This fixes the scenario where the project has a direct dependency to a package and another direct dependency has a transitive dependency to the same one. By inferring the latter as an implicit dependency, we overwrite the pack attributes of the former.
> Never infer implicit reference for existing direct reference

- src/CodeAnalysis/CodeAnalysis.csproj
- src/CodeAnalysis/NuGetizer.CodeAnalysis.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.targets
For development-dependency packages, no assets flow across project references, including build targets and package dependencies. This is problematic for SponsorLink since it needs targets to properly surface build properties to the analyzer that performs the checks.
By making NuGetizer build targets transitive, we fix the project to project (P2P) scenario where one project installs NuGetizer and referencing projects start failing the SponsorLink check because the SL targets are missing. (since the package dependency on SL isn't surfaced in that case).
By also including the SL targets in our package and conditionally importing them if they haven't already been imported, we further remove the changes that the missing dependency causes failures.
This might not be the optimal way to solve …
> Make NuGetizer targets buildTransitive to fix SponsorLink

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
This stops inference from collecting transitive dependency files from NuGetizer and packing them too alongisde the consuming project.
This is currently an issue since due to being a development dependency, NuGetizer will by default install with a `PrivateAssets=all` value, which for packing purposes means "pack everything this dependency brings, transitively, into this package output", since that's the most common scenario.
But for build-only packages like NuGetizer, it doesn't make sense. Especially for non-build transitive assets such as analyzer's localization files (i.e. SponsorLink in NuGetizer's case).
So we default this to the most obvious value now.
> Never pack NuGetizer transitively

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.Shared.targets
Since analyzers are transitive by default (unless PrivateAssets=all in the PackageReference), we could have been inadvertently running SL checks via project-to-project (P2P) references and causing build errors since SL requires some compiler-visible properties surfaced via MSBuild that would otherwise not be available.
This can happen if you add a package reference manually and forget to set PrivateAssets=all. But NuGetizer is *always* intended to be private assets.
After some testing, it turns out that even if we set the PrivateAssets=all via targets provided by the package itself, we can prevent this abnormal (but perhaps easy to encounter?) situation from happening at all.
This is particularly necessary with the introduction of the SponsorLink checks, since those are analyzers too, and …
> Ensure private assets always for NuGetizer

- src/CodeAnalysis/CodeAnalysis.csproj
- src/CodeAnalysis/NuGetizer.CodeAnalysis.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.targets
This is no longer needed now that we update NuGetizer package reference to always be PrivateAssets=all, to account for users not doing it (misconfig issue).
This also fixes the issue with multi-targeting projects referencing nugetizer now since we had the wrong path for importing targets in that case.
> Revert changes to make build targets transitive

- src/NuGetizer.Tasks/NuGetizer.Shared.targets
This prevents transitive packing of SponsorLink analyzer localization resources, for example.
> NuGetizer should always be Pack=false

- src/NuGetizer.Tasks/NuGetizer.Cleanup.targets
Since non-packaging projects might be built multiple times without producing packages, cleaning after every build is not only wasteful (in terms of processing/time) but can also break other currently opened solutions and require force-restoring.
Fixes #369
> Clean package cache only after packing

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/InlineProjectTests.cs
As a package author, you might consume a development dependency for your own authoring, but also might want to take a dependency on it in your package. GitInfo is an example.
We want to make sure we honor explicit Pack=true even if a package has PrivateAssets=all (which has different use cases too).
Fixes #281
> Make sure we can explicitly pack a privateassets/development dependency

- src/NuGetizer.Tasks/NuGetizer.Shared.targets
- src/NuGetizer.Tasks/NuGetizer.Tasks.csproj
Now that SponsorLink is OSS and based on received feedback it will change in many ways moving forward, we'll for now remove the current implementation from the package to address the issues that were raised.
See https://github.com/devlooped/SponsorLink
> Remove current implementation of SponsorLink for now

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
We were duplicating the logic for package readme files instead of package icon due to duplicated code.
Fixes #436
> Fix copy error in inference targets for package icon

- src/NuGetizer.Tasks/NuGetizer.Authoring.props
- src/NuGetizer.Tasks/NuGetizer.Compatibility.props
- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tasks/NuGetizer.targets
- src/NuGetizer.Tests/given_a_packaging_project.cs
Since a packaging project (for example) doesn't actually contain build artifacts but can still default its root content to a framework-specific folder, we should instead adopt the uniform `Pack*` prefix we now use everywhere.
Fixes #438
> Rename BuildOutputFrameworkSpecific > PackFrameworkSpecific for consistency

- src/dotnet-nugetize/Program.cs
Make sure nugetize always sets EnablePackageValidation=false to avoid SDK attempting to validate a non-existent package
Fixes #482
> Don't fail with SDK trying to validate package on nugetize

- src/CodeAnalysis/CodeAnalysis.csproj
- src/NuGetizer.Tasks/NuGetizer.Tasks.csproj
- src/NuGetizer.Tests/NuGetizer.Tests.csproj
- src/dotnet-nugetize/dotnet-nugetize.csproj
> Remove SourceLink packages which are now built-in the .NET SDK

- .github/workflows/build.yml
- .github/workflows/publish.yml
Since tests aren't actually building stuff, the workloads don't really need to be installed.
> Remove workload restore to speed up build

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/Scenarios/given_transitive_projects/Project1.csproj
- src/NuGetizer.Tests/Scenarios/given_transitive_projects/Project2.csproj
- src/NuGetizer.Tests/Scenarios/given_transitive_projects/Project3.csproj
- src/NuGetizer.Tests/given_transitive_projects.cs
Turns out that the .NET SDK lifts transitive project references as direct references (without any additional metadata), and this causes the second-level dependency from being built unexpectedly (see https://github.com/dotnet/sdk/pull/478 and https://github.com/dotnet/project-system/issues/199).
Since we don't want to disrupt the IDE (BuildingInsideVisualStudio) and we only want to fix this for the very specific case of running from the CLI `dotnet pack --no-build`, we make the fix very constrained for that scenario. We check for `NoBuild` but ALSO for `_IsPacking`, which is passed by the `dotnet pack` command.
This ensures minimal impact in all other scenarios, since we're essentially turning off a built-in behavior in the SDK that has explicit side-effects (by design and desirable) and …
> Additional fix for --no-build in pack with transitive references

- src/dotnet-nugetize/Program.cs
This is typically unnecessary regardless of what setting users use for cleanup.
> When running nugetize, never cleanup built packages

- src/NuGetizer.Tasks/NuGetizer.Inference.targets
- src/NuGetizer.Tests/given_a_tool_project.cs
Fix issue with localized resources when packing tools
We were missing the %(RecursiveDir) value which caused localized resources to end up as duplicate assets in the package, causing the pack to fail.
> Fix issue with localized resources when packing tools
